{% set name = "spectral" %}
{% set version = "0.19" %}
{% set sha256 = "b8d5dc9e2e36d45d1f55bf95528a63d7a95dd049857c98f86d400a3f0c7c86f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - spectral

about:
  home: https://github.com/spectralpython/spectral/
  license: GPLv2
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'A Python module for hyperspectral image processing.'
  description: |
    A pure Python module for processing hyperspectral image data (imaging spectroscopy data). 
    It has functions for reading, displaying, manipulating, and classifying hyperspectral 
    imagery. SPy is Free, Open Source Software (FOSS) distributed under the GNU General Public License.
  doc_url: http://spectralpython.net
  dev_url: https://github.com/spectralpython/spectral/

extra:
  recipe-maintainers:
    - lewismc
    - tboggs
