{% set name = "spectral" %}
{% set version = "0.22" %}
{% set sha256 = "e37672282d850ebf999feb4bbf67e7cd3291b4eb550e41d6a49701485d341e40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - spectral

about:
  home: https://github.com/spectralpython/spectral/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python module for hyperspectral image processing.
  description: |
    A pure Python module for processing hyperspectral image data (imaging spectroscopy data). 
    It has functions for reading, displaying, manipulating, and classifying hyperspectral 
    imagery. SPy is Free, Open Source Software (FOSS) distributed under the MIT License.
  doc_url: http://spectralpython.net
  dev_url: https://github.com/spectralpython/spectral/

extra:
  recipe-maintainers:
    - lewismc
    - tboggs
