travis:
  secure:
    BINSTAR_TOKEN: gJIWJfqvb2QUOD6VjjbeAHjJf3rdHA4zC/AUTKdbMsx2F0zyA4Z6/VgF8bVlAnQE/C+7Q5S1JT5nC1PQACfhaRDmi6e2EG4504fzJfci4z7mGNojHAJdupPtEy01OFbbv9K9uCDRMxBbA6AIsseAXWiSr/NPfGQyRwYLRN4z23enQPRkHIE9LVSoa56gXWMdeyl0a32Fhx6uyO3qWULKfhcbKzy+3P72LhfGnEUvAuv0rxXKUYUGMevOvRtEVjVBU3QzTMvUjooI6hHxIuNEM6kW45OnLt8b/VTQk2NlR0aJQdCmFYIdxQU1X4XxaFAmcMgJ3ofEUWhmEJJBCZmZlrVMWjn5vJj7RHn1vl42VR1XLJy6Dhv5MGjqGUOlreHQkIMkJPfpNWajCUaw8p+Zu0+pV5lbwZtDkxJ886BttHXwQjEH12vIArmIOFyWVVn4pk8wujWJ2CUdUNB/KbyIOnpM/lMi4r3hWC1gtl1humUkqfCZQ6Q+JcWjeYQFVh4CpgqukErMv365gew+0SBNVgBzfuW/GmX1pfwy1jAXz3BaCRKcCTxPtwDzrpf44wcRrgzITiqz/i+5dpUWqxH5DYxw7dYqzh4gWFbZiLwMKHKP5btjyGiFAQ0E8OA8/O97WXy6BJwRbtDYchV/JaKnm5m8aN8eFR9xZo79KxBmk9g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
