travis:
  secure:
    BINSTAR_TOKEN: k5gxWYAeTQImVbaWjdJyQgKmK0XMp+xXam1GO7P+GzHogowSOgVcvN7PzOOAMXwaEXTLe/n517sF1mDGqD9giDtrSgDeKCzORIUJ0p1Mo/1H3/GRTCub6XFQ38PZecw2u2V7LBKzTivvFKbezq+xizR0lmOFxfiPGc6CGDDaWZfTyHSuYj2JfPi0fB9CavfhNfl6F0xkwWFYuGyHcu5bmuNxnnmZh4vCZyN+gRnuq5BGFHAFNPLFqpSaIbS1MS5aNaq2ntYjUMEjkcFIuHXpMEKK997aquKeteoJW+sV36Wf7Pk75I90VYrXrOAxhqU6tFqgfpLLojL/xqJrOKXxgNDW8GMAw02BwXFYFSI3r4JiDqltzIO6LJTOcd04507GzwAirztCb22qYnyM5Qh4SX+n4akYMTMQEapCaEoJq07A/DXKw4LI8rFpB/Vi1Qk8kaXpCtPfOm+ClqLALSPBCbhBClpJsWOhppT/R0SvFfcAfsh1140xU9xWqjLWqalUBmNGxMu6a+POyBplfFsVhz2iBk1CSjic1g543rgDBVxE8G0Alz7PO3nG5TQ64oH4VE2xRVYuyehrooQTqqJdSU2Zg3olQR0zn3eQ/KtpM9UHznd1/2Gb9c3Di3rMAclM7lPbapgw3csM0UnglPGPR2/MBCHggxq8IoDGefGavx4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
